language: python
python:
  - '3.7'
cache: pip
install:
  - pip install -r src/elasticsearch/addl_index_transformations/requirements.txt
  - pip install -r src/elasticsearch/addl_index_transformations/requirements-dev.txt
script:
  - src/elasticsearch/addl_index_transformations/test.sh
