# http://docs.travis-ci.com/user/customizing-the-build/#Git-Submodules
git:
  submodules: false
  
before_install:
  # https://gist.github.com/iedemam/9830045
  # - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
  #
  # https://git-scm.com/docs/git-submodule#_options:
  # --remote
  # Instead of using the superproject’s recorded SHA-1 to update the submodule,
  # use the status of the submodule’s remote-tracking (branch.<name>.remote) branch (submodule.<name>.branch).
  # --recursive
  # https://github.com/travis-ci/travis-ci/issues/4099
  - git submodule update --init --remote --recursive

language: python
python:
  - "3.9"
services:
  - elasticsearch
before_script:
  - sleep 10  # Advised by https://docs.travis-ci.com/user/database-setup/#elasticsearch
install:
  - pip install -r src/search-adaptor/src/requirements.txt
  - pip install -r src/search-adaptor/src/requirements-dev.txt
script:
  - ./test.sh
