language: python
python:
  - '3.7'
cache: pip
before_install:
  # From https://docs.travis-ci.com/user/database-setup/#installing-specific-versions-of-elasticsearch
  # (Version matches that used on AWS.)
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.2-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart
before_script:
  - sleep 10  # Advised by https://docs.travis-ci.com/user/database-setup/#elasticsearch
env:
  - COMMONS_BRANCH=master
install:
  - pip install -r src/requirements.txt
  - pip install -r src/requirements-dev.txt
script:
  - ./test.sh
