openapi: 3.0.0
info:
  description: The HuBMAP Search API is a thin wrapper of the Elasticsearch. It handles data indexing and reindexing into the backend Elasticsearch. It also accepts the search query and passes through to the Elasticsearch with data access security check.
  version: "0.1.0"
  title: HuBMAP Search API
  termsOfService: "https://hubmapconsortium.org"
  contact:
    email: apiteam@hubmap.org

tags:
  - name: Search API, Elasticsearch
    description: Operations pertaining to datasets indexed in Elasticsearch

paths:
  /search:
    post:
      tags:
        - search
      summary: Execute an Elasticsearch query JSON via HTTP POST and get back search hits that match the query
      operationId: search-post
      responses:
        "200":
          description: Returns search hits from backend Elasticsearch that match the query defined in the request JSON
        "400":
          description: A JSON body and appropriate Content-Type header are required in request
        "401":
          description: A valid globus token in the `Authorization` header (Bearer scheme) is required in request
        "403":
          description: The globus token used in the `Authorization` header doesn't have the right group access permission
    get:
      tags:
        - search
      summary: Execute an Elasticsearch query JSON via HTTP GET and get back search hits that match the query
      operationId: search-get
      responses:
        "200":
          description: Returns search hits from backend Elasticsearch that match the query defined in the request JSON
        "400":
          description: A JSON body and appropriate Content-Type header are required in request
        "401":
          description: A valid globus token in the `Authorization` header (Bearer scheme) is required in request
        "403":
          description: The globus token used in the `Authorization` header doesn't have the right group access permission
          
  "/reindex/{identifier}": 
    put:
      tags:
        - reindex
      summary: Reindex for a given UUID of dataset
      operationId: reindex
      parameters:
        - name: identifier
          in: path
          description: The unique identifier of collection.  This must be a UUID.
          required: true
          schema:
            type: string
      responses:
        "202":
          description: The request has been accepted and reindex is in process
