version: "3.7"

services:
  
  search-api:
    environment:
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
    init: true
    restart: always
    volumes:
      # Indexer logging
      - "../src/log:/usr/src/app/src/log"

