version: "3.7"

# Will use the hostname when talking between services on the same network
services:
  
  search-api:
    build: ./search-api
    # Build the image with name and tag
    image: search-api:1.0
    hostname: search-api
    container_name: search-api
    environment:
      - HOST_GID=1000
      - HOST_UID=1000
    volumes:
      # Mount the app config to container in order to keep it outside of the image
      - "../src/instance:/usr/src/app/src/instance"
      # Mount the logging to container
      - "../log:/usr/src/app/log"
    networks:
      - gateway_hubmap

  hubmap-elasticsearch:
    image: elasticsearch:7.5.2
    hostname: hubmap-elasticsearch
    container_name: hubmap-elasticsearch
    environment:
      # Start a single-node Elasticsearch cluster for development to bypass the bootstrap checks
      - discovery.type=single-node
    networks:
      - gateway_hubmap
    ports:
      - "9200:9200"
    volumes:
      # Mount data for data persistence cross container restarts
      - "./data:/usr/share/elasticsearch/data"
      # Mount logging files from container to host
      - "./logs:/usr/share/elasticsearch/logs"

  hubmap-kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    hostname: hubmap-kibana
    container_name: hubmap-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://hubmap-elasticsearch:9200
    networks:
      - gateway_hubmap
    ports:
      - "5601:5601"
    depends_on:
      - hubmap-elasticsearch

networks:
  # This is the network created by gateway to enable communicaton between multiple docker-compose projects
  gateway_hubmap:
    external: true
