settings:
  index:
    # Increased from 5000 to 6000 to cater the duplicated fields
    # will bump this limit back down once the duplicated fields removed
    # noted by Zhou 6/28/2021
    mapping.total_fields.limit: 6000
    query.default_field: 2048

mappings:
  date_detection: False
  dynamic_templates:
    -
      map_every_string:
        match_mapping_type: string
        mapping:
          copy_to: all_text
          type: text
          fields:
            # This emulates the default ES behavior,
            # giving us a "keyword" subfield,
            # with a "keyword" type.
            keyword:
              type: keyword
