settings:
  index:
    mapping.total_fields.limit: 5000
    query.default_field: 2048

mappings:
  date_detection: False
  dynamic_templates:
    -
      copy_every_string_to_all_text:
        match_mapping_type: string
        mapping:
          # TODO: "all_text" will replace the "everything" field.
          copy_to: all_text
          type: text
    -
      copy_every_string_to_keyword:
        match_mapping_type: string
        mapping:
          # This is the default behavior when no mapping is specified.
          # Sorting results on the portal requires keyword fields to exist.
          copy_to: '{name}.keyword'
          type: keyword
